# Implement in Python

In [1]:
import numpy as np
A = np.array([[1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
              [1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
              [1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
              [1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
              [1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],])
print(A)
m, n = A.shape
print(m) #Rows
print(n) #Cols

[[ 1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
10
10


## Implement Kernels

In [2]:
kerA = np.array([[1, -1],
                [1, -1]])
print('Kernel A\n', kerA, '\n')

kerB = np.array([[1, 1],
                [-1, -1]])
print('Kernel B\n', kerB)

Kernel A
 [[ 1 -1]
 [ 1 -1]] 

Kernel B
 [[ 1  1]
 [-1 -1]]


## Convolution

In [3]:
s = (5, 5)
B = np.zeros(s)
C = np.zeros(s)
print(B)
print(C)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [4]:
def Convolution(Target, New, Kernel, n):
    #Index in target matrix
    a = 0
    b = 0
    #
    c = 1
    d = 0
    #Comparison variable
    val = 2
    #Index for new matrix
    inda = 0
    indb = 0
    #Check for end of matrix
    num = 4

    for i in np.arange(Target.size / 4):
        val = 2
        #Compare and find greatest value
        tempa = Target[a, b] * Kernel[0, 0]
        tempb = Target[a, b + 1] * Kernel[0, 1]
        tempc = Target[c, d] * Kernel[1, 0]
        tempd = Target[c, d + 1] * Kernel[1, 1]
        #Put value in new matrix
        New[inda, indb] = (tempa + tempb + tempc + tempd)
        #Increment new matrix index over by row
        indb += 1
        #Move kernel horizontally
        b += 2
        d += 2
        #When at end of matrix increment index by column
        if i == (n - 1) or (num + n) == i:
            #Move kernel vertically, reset horizontal index
            a += 2
            c += 2
            b = 0
            d = 0
            #Increment new matrix index over by column, reset horizontal index
            inda += 1
            indb = 0
            #Used for each time i + 5
            num = i
    return New

B = Convolution(A, B, kerA, 5)
C = Convolution(A, C, kerB, 5)



## Turn matrix to image

In [5]:
import cv2
cv2.imshow('Image', B)
cv2.waitKey()
cv2.destroyAllWindows()

cv2.imshow('Image', C)
cv2.waitKey()
cv2.destroyAllWindows()


# On real image

In [6]:
#0 = black, 255 = white

img = cv2.imread('img.jpg',cv2.IMREAD_GRAYSCALE)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Normalize img -1 to 1
newImg = (img / 128) - 1
#Create size for new image
m, n = newImg.shape
s = (200, 300)
D = np.zeros(s)
E = np.zeros(s)
D = Convolution(newImg, D, kerA, n / 2)
E = Convolution(newImg, E, kerB, n / 2)

cv2.imshow('Kernal A', D)
cv2.waitKey()
cv2.destroyAllWindows()

cv2.imshow('Kernal A', E)
cv2.waitKey()
cv2.destroyAllWindows()